name: push

on:
  push:
    branches:
      - '*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
          path: bungee

      - name: 🛠️ Configure, build and install linux-x86_64
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: 2
          PRESET: linux-x86_64
        run: |
            cmake \
              --preset ${PRESET} \
              -S ${{github.workspace}}/bungee \
              -B ${{github.workspace}}/builds/${PRESET} \
              -G "Unix Makefiles"
            cmake \
              --build ${{github.workspace}}/builds/${PRESET}/
